// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableVoices():Promise<Array<string>>;

export function GetContent():Promise<string>;

export function GetCurrentFile():Promise<string>;

export function IsSpeaking():Promise<boolean>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SpeakLine(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Stop():Promise<void>;
